---
title: "DAYMET Data clean"
author: "Tolu"
date: "6/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE, warning=FALSE}
library(knitr)
library(dplyr)
library(tidyverse)
library(plotly)
library(gridExtra)
library(vars)
library(urca)
library(MASS)
library(stargazer)
library(sf)
library(stringi)
library(leaflet)
library(raster)
library(tmap)
library(mapdeck)
library(mapview)
library(RColorBrewer)
library(ggplot2)
library(gganimate)
library(gapminder)
library(transformr)
library(gifski)
library(ggrepel)
library(hrbrthemes)
library(FedData)
library(magrittr)
library(daymetr)
library(lubridate)
library(maps)
library(tigris)
library(ncdf4)
```


```{r}
VA_counties <- maps::map("county", "virginia", plot = FALSE, fill = TRUE) %>% 
  st_as_sf()
```

```{r}
VA_counties_select <- filter(VA_counties, ID %in% c("virginia,albemarle", "virginia,Charlottesville", "virginia,fluvanna", "virginia,greene", "virginia,louisa", "virginia,nelson", "virginia,accomack", "virginia,northampton"))
```

```{r}
VA_daymet_select <- (FedData::get_daymet(
  #--- supply the vector data in sp ---#
  template = as(VA_counties_select, "Spatial"), 
  #--- label ---#
  label = "VA_counties_select",
  #--- variables to download ---#
  elements = "tmax",
  #--- years ---#
  years = 1980:2020))
raster::plot(VA_daymet_select$X1985.10.23)
```

